### ISSUE TITLE
Pysindy and Derivative dependencies are outdated

### ISSUE THREAD

**Issue by yb6599** [Jacob-Stevens-Haas/gen-experiments#27]
Hey @Jacob-Stevens-Haas, the dependencies for pysindy and derivative in`pyproject.toml` are outdated, they cause issues when I upgrade gen-experiments for the Kalman SINDy PDE experiments. Should I update the dependencies to the latest versions?

**Comment by Jacob-Stevens-Haas** [comment]
Yes
