### ISSUE TITLE
Smoothed Finite Difference instead of Savitzky Golay in config

### ISSUE THREAD

**Issue by yb6599** [Jacob-Stevens-Haas/gen-experiments#28]
Hey @Jacob-Stevens-Haas, I came across this in `config.py`:
```
    "sg1": SeriesDef(
        "Savitsky-Golay",
        diff_params["sfd-ps"],
        ["diff_params.smoother_kws.window_length"],
        [[5, 7, 15]],
    ),
    "sg2": SeriesDef(
        "Savitsky-Golay",
        diff_params["sfd-ps"],
        ["diff_params.smoother_kws.window_length"],
        [[5, 8, 12, 15]],
    ),
```
This is supposed to be Savitzky Golay Smoothing, so should it not be `diff_params["savgol"]` instead of `diff_params["sfd-ps"]`. What should I use during the pde experiments?

**Comment by Jacob-Stevens-Haas** [comment]
I believe that we're using the `pysindy` implementation of Savitzky-Golay, rather than the `derivative` one.  What are the values of `diff_params["sfd-ps"]` and `diff_params["savgol"]`?

**Comment by yb6599** [comment]
The values are:
```
"sfd-ps": ND({"diffcls": "SmoothedFiniteDifference", "axis":-2}),
"savgol": ND({"diffcls": "sindy", "kind": "savitzky_golay", "axis": -2, "left":0.1, "right":0.1, "order":3}),
```

**Comment by Jacob-Stevens-Haas** [comment]
I would use `diff_params["sfd-ps"]`

**Comment by yb6599** [comment]
Got it
