### ISSUE TITLE
Issues with the max_amplitude function

### ISSUE THREAD

**Issue by yb6599** [Jacob-Stevens-Haas/gen-experiments#29]
Hey @Jacob-Stevens-Haas , this is about the max amplitude function we changed. it is written as 
```
def _max_amplitude(signal: np.ndarray, axis: int) -> float:
    return np.abs(scipy.fft.rfft(signal, axis=axis)[1:]).max() / np.sqrt(
        signal.shape[axis]
    )
```
I don't understand the significance of `[1:]`, but the error I am getting originates there, which is
```
ValueError: zero-size array to reduction operation maximum which has no identity
```
where `scipy.fft.rfft(signal, axis=axis)` is an array of shape `(1, 51, 256)`, so `scipy.fft.rfft(signal, axis=axis)[1:]` returns an empty array
I am assuming that since we have ODEs shaped as (t, x) and PDEs shaped as (x, t, d), for PDE purposes, should it be [:, 1:, :], or something else?

**Comment by Jacob-Stevens-Haas** [comment]
To clarify, have ODEs shaped as `[n_time, n_coord]` and PDEs shaped as `[*n_spatial, n_time, n_coord]`.  I believe the signal you have should be shaped as `(51, 256, 1)` or `(256, 51, 1)`

The `:1` is to drop the constant term, since the 0th element of the Fourier transform is  the constant term.

**Comment by yb6599** [comment]
Alright, got it.
